@startuml
class HotelsController {
    + HotelsController(publishEndpoint:IPublishEndpoint)
    + <<async>> GetAvailableRooms(request:AvailableRoomsRequest) : Task<ActionResult>
}
ControllerBase <|-- HotelsController
@enduml
