@startuml
class GetTripByPreferencesEvent {
    + Destination : string <<get>> <<set>>
    + DeparturePlace : string <<get>> <<set>>
    + NumOfAdults : int <<get>> <<set>>
    + NumOfKidsTo18 : int <<get>> <<set>>
    + NumOfKidsTo10 : int <<get>> <<set>>
    + NumOfKidsTo3 : int <<get>> <<set>>
}
GetTripByPreferencesEvent --> "Id" Guid
GetTripByPreferencesEvent --> "CorrelationId" Guid
GetTripByPreferencesEvent --> "DepartureDate" DateTime
@enduml
