@startuml
!include .\\ApiGateway\Program.puml
!include .\\FlightService\Program.puml
!include .\\HotelService\Program.puml
!include .\\PaymentService\Program.puml
!include .\\Shared\Class1.puml
!include .\\TripService\Program.puml
!include .\\ApiGateway\Controllers\TripController.puml
!include .\\FlightService\Consumers\GetAvailableFlightsEventConsumer.puml
!include .\\FlightService\Consumers\ReserveSeatsEventConsumer.puml
!include .\\FlightService\Data\FlightContext.puml
!include .\\FlightService\Data\FlightRepo.puml
!include .\\FlightService\Data\IFlightRepo.puml
!include .\\HotelService\Consumers\AvailableRoomsConsumer.puml
!include .\\HotelService\Controllers\HotelsController.puml
!include .\\HotelService\Data\HotelDbContext.puml
!include .\\HotelService\Data\HotelRepo.puml
!include .\\HotelService\Data\IHotelRepo.puml
!include .\\HotelService\Models\Hotel.puml
!include .\\HotelService\Models\Room.puml
!include .\\HotelService\Models\RoomEvent.puml
!include .\\PaymentService\Consumers\ProcessPayment.puml
!include .\\TripService\Consumers\GetAllTripsConsumer.puml
!include .\\TripService\Consumers\GetTripsByPreferencesConsumer.puml
!include .\\TripService\Consumers\GetTripsByUserIdConsumer.puml
!include .\\TripService\Data\AppDbContext.puml
!include .\\TripService\Data\ITripRepo.puml
!include .\\TripService\Data\PrepDb.puml
!include .\\TripService\Data\TripRepo.puml
!include .\\TripService\Models\Trip.puml
!include .\\FlightService\Data\Tables\FlightEntity.puml
!include .\\FlightService\Data\Tables\FlightEvent.puml
!include .\\Shared\Flight\Dtos\FlightDto.puml
!include .\\Shared\Flight\Events\GetAvailableFlightsEvent.puml
!include .\\Shared\Flight\Events\GetAvailableFlightsEventReply.puml
!include .\\Shared\Flight\Events\ReserveSeatsEvent.puml
!include .\\Shared\Flight\Events\ReserveSeatsEventReply.puml
!include .\\Shared\Hotel\Events\AvailableRoomsRequest.puml
!include .\\Shared\Payment\Events\ProcessPaymentFromCustomer.puml
!include .\\Shared\Payment\Events\ProcessPaymentToCustomer.puml
!include .\\Shared\Trip\Dtos\TripDto.puml
!include .\\Shared\Trip\Events\CreateTripEvent.puml
!include .\\Shared\Trip\Events\GetAllTripsEvent.puml
!include .\\Shared\Trip\Events\GetTripByPreferencesEvent.puml
!include .\\Shared\Trip\Events\GetTripsByUserIdEvent.puml
!include .\\Shared\Trip\Events\ReplyTripsDtosEvent.puml
!include .\\ApiGateway\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\ApiGateway\obj\Debug\net8.0\ApiGateway.AssemblyInfo.puml
!include .\\ApiGateway\obj\Debug\net8.0\ApiGateway.GlobalUsings.g.puml
!include .\\ApiGateway\obj\Debug\net8.0\ApiGateway.MvcApplicationPartsAssemblyInfo.puml
!include .\\FlightService\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\FlightService\obj\Debug\net8.0\FlightService.AssemblyInfo.puml
!include .\\FlightService\obj\Debug\net8.0\FlightService.GlobalUsings.g.puml
!include .\\FlightService\obj\Debug\net8.0\FlightService.MvcApplicationPartsAssemblyInfo.puml
!include .\\HotelService\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\HotelService\obj\Debug\net8.0\HotelService.AssemblyInfo.puml
!include .\\HotelService\obj\Debug\net8.0\HotelService.GlobalUsings.g.puml
!include .\\HotelService\obj\Debug\net8.0\HotelService.MvcApplicationPartsAssemblyInfo.puml
!include .\\PaymentService\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\PaymentService\obj\Debug\net8.0\PaymentService.AssemblyInfo.puml
!include .\\PaymentService\obj\Debug\net8.0\PaymentService.GlobalUsings.g.puml
!include .\\PaymentService\obj\Debug\net8.0\PaymentService.MvcApplicationPartsAssemblyInfo.puml
!include .\\Shared\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\Shared\obj\Debug\net8.0\Shared.AssemblyInfo.puml
!include .\\Shared\obj\Debug\net8.0\Shared.GlobalUsings.g.puml
!include .\\TripService\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\TripService\obj\Debug\net8.0\TripService.AssemblyInfo.puml
!include .\\TripService\obj\Debug\net8.0\TripService.GlobalUsings.g.puml
!include .\\TripService\obj\Debug\net8.0\TripService.MvcApplicationPartsAssemblyInfo.puml
@enduml
