@startuml
class WeatherForecast <<record>> {
    + TemperatureC : int <<get>> <<init>>
    + Summary : string? <<get>> <<init>>
    + TemperatureF : int <<get>>
}
class "AddDbContext`1"<T> {
}
class "AddScoped`2"<T1,T2> {
}
class "AddConsumer`1"<T> {
}
WeatherForecast --> "Date" DateOnly
@enduml
